# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\eclipse_workspace\PyQt5Test\src\UMHelper2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 596)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(210, 20, 571, 511))
        self.stackedWidget.setObjectName("stackedWidget")
        
        self.page_index = QtWidgets.QWidget()
        self.page_index.setObjectName("page_index")
        self.label = QtWidgets.QLabel(self.page_index)
        self.label.setGeometry(QtCore.QRect(210, 140, 161, 21))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_index)
        self.page_relic = QtWidgets.QWidget()
        self.page_relic.setObjectName("page_relic")
        self.label_2 = QtWidgets.QLabel(self.page_relic)
        self.label_2.setGeometry(QtCore.QRect(250, 10, 72, 15))
        self.label_2.setObjectName("label_2")
        #圣物列表
        '''
        #安装圣物列表页下侧的按钮
        self.gridLayout2 = QtWidgets.QGridLayout(self.page_relic)
        self.gridLayout2.setGeometry(QtCore.QRect(0, 30, 541, 491))
        self.gridLayout2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout2.setObjectName("gridLayout2")
        '''
        self.tableWidget = QtWidgets.QTableWidget(self.page_relic)
        self.tableWidget.setGeometry(QtCore.QRect(0, 30, 541, 491))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        
        self.stackedWidget.addWidget(self.page_relic)
        
        self.page_potion = QtWidgets.QWidget()
        self.page_potion.setObjectName("page_potion")
        self.label_3 = QtWidgets.QLabel(self.page_potion)
        self.label_3.setGeometry(QtCore.QRect(250, 10, 72, 15))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_potion)
        self.page_showRelic = QtWidgets.QWidget()
        self.page_showRelic.setObjectName("page_showRelic")
        self.widget = QtWidgets.QWidget(self.page_showRelic)
        self.widget.setGeometry(QtCore.QRect(0, 0, 531, 511))
        self.widget.setObjectName("widget")
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.tableWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 0, item)
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(74)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.tableWidget_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.stackedWidget.addWidget(self.page_showRelic)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 121, 531))
        self.layoutWidget.setObjectName("layoutWidget")

        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")

        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        #安装左侧栅格布局的按钮
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.pushButton_5, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.pushButton_6, 5, 0, 1, 1)
        
        self.layoutWidget.raise_()
        self.stackedWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        #设置按钮图片
        self.set_style_sheet(self.pushButton, "../images/icon.png")
        self.set_style_sheet(self.pushButton_2, "../images/Relics/Paladin Shield.png")
        self.set_style_sheet(self.pushButton_3, "../images/2.png")
        self.set_style_sheet(self.pushButton_4, "../images/3.png")
        self.set_style_sheet(self.pushButton_5, "../images/4.png")
        self.set_style_sheet(self.pushButton_6, "../images/5.png")
        self.set_style_sheet(self.pushButton_7, "../images/UI_Return.png")
        self.set_style_sheet(self.pushButton_8, "../images/UI_LeftArrow.png")
        self.set_style_sheet(self.pushButton_9, "../images/UI_RightArrow.png")
        self.retranslateUi(MainWindow) #翻译器
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_7.clicked.connect(self.pushButton_2.click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        

    def retranslateUi(self, MainWindow):
        #通过查询已安装的翻译文件返回sourceText的翻译文本
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UnderMine图鉴手册V0.2.2"))
        MainWindow.setWindowIcon(QtGui.QIcon("../images/icon.png"))
        self.label.setText(_translate("MainWindow", "UnderMine图鉴手册"))
        self.label_2.setText(_translate("MainWindow", "圣物图鉴"))
        '''
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "韦兰之靴"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        '''
        self.label_3.setText(_translate("MainWindow", "药水图鉴"))
        self.pushButton_7.setText(_translate("MainWindow", "返回"))
        self.lineEdit_2.setText(_translate("MainWindow", "Relic_name"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建列"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("MainWindow", "编号"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("MainWindow", "稀有度"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("MainWindow", "解锁方式"))
        item = self.tableWidget_2.item(4, 0)
        item.setText(_translate("MainWindow", "独特圣物"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">效果：</p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">简评：</p></body></html>"))
        self.lineEdit.setText(_translate("MainWindow", "评分："))
        self.pushButton.setText(_translate("MainWindow", "首页"))
        self.pushButton_2.setText(_translate("MainWindow", "圣物"))
        self.pushButton_3.setText(_translate("MainWindow", "药水"))
        self.pushButton_4.setText(_translate("MainWindow", "祝福"))
        self.pushButton_5.setText(_translate("MainWindow", "诅咒"))
        self.pushButton_6.setText(_translate("MainWindow", "同伴"))
    
    #设置按钮图片样式
    @staticmethod    
    def set_style_sheet(pushbutton, pic_path=None):
        style = """
        QPushButton{
        background: #426F42 no-repeat center;
        border: 5px solid #5C3317;
        border-radius: 8px;
        font-size: 20px;
        color: white;
        font-family: "微软雅黑", "宋体", sans-serif;
        }
        QPushButton:hover{
        border: 5px solid #A67D3D;
        color: #FFFF00;
        }
        QPushButton:pressed{
        border: 5px solid #CFB53B;
        }
        """
        pushbutton.setStyleSheet(style)
        if pic_path:
            pushbutton.setIcon(QtGui.QIcon(pic_path))
            pushbutton.setIconSize(QtCore.QSize(40, 40))
        